### PR TITLE
Enable AddRedis only if chain to AddSignalR

### PR DESCRIPTION
**Pull request by Xiaohongt**
This is related to aspnet/SignalR-Server#65.

Enable AddRedis only if chain to AddSignalR

### CODE REVIEW

**Comment by Xiaohongt** [comment]
@BrennanConroy , this is for Redis change

**Comment by BrennanConroy** [comment]
This is good, but hold off pushing it until the server package is live

**Comment by halter73** [comment]
:ship:

**Comment by halter73** [comment]
We probably want to change this to use ServiceDescriber like the SignalR-Server and SignalR-SqlServer projects before we :shipit:.

**Comment by BrennanConroy** [comment]
:shipit:

**Pull request closed without merging**
